### ISSUE TITLE
Take branch/tag/SHA as input to output dir

### ISSUE THREAD

**Issue by tingvarsson** [cheald/dxvk-docker#1]
Improvement suggestion would be to take the branch/tag/SHA provided as input to output dir instead of hardcorded dxvk-master.
e.g. branch d3d10 => output dir: dxvk-d3d10
make-dxvk is straight forward, just use gitref instead of hardcorded string. But you'll have to do some parameter passing to the docker image/build.sh to replace its argument to package-release.sh.

**Comment by cheald** [comment]
Not a bad idea. Would make it easy to run multiple concurrent versions. Closed via https://github.com/cheald/dxvk-docker/commit/f06b6b0c322ed5efe1d16b9c47d34bbbc507f4cc

**Comment by tingvarsson** [comment]
Thanks for the quick response and nice work!
