### ISSUE TITLE
Runs on local branch of dxvk, does not update to origin/master on 2nd attempt

### ISSUE THREAD

**Issue by tingvarsson** [cheald/dxvk-docker#2]
The script make-dxvk will do git fetch -a and checkout given gitref, but will not update local gitrefs to match remote ones.
E.g. I provide master as wanted branch and it pulls down dxvk and checkouts master. If I do it a second time and remote (origin) master is updated I will still build my local master branch.

I guess I would have to provide origin/master for the script to actually build latest master from github.

**Comment by cheald** [comment]
I think that's probably best left untouched; one might want to build a local master! Any thoughts on how to handle both cases gracefully?

**Comment by cheald** [comment]
After trying it out, I think it does need to fetch from origin by default. I've updated make-dxvk via https://github.com/cheald/dxvk-docker/commit/f06b6b0c322ed5efe1d16b9c47d34bbbc507f4cc to do so. If folks want to build their own local modifications, they'll probably have a build env set up anyhow.

**Comment by tingvarsson** [comment]
Thought some about it during the day and didnt come up with a nice way to do it. But probably force "remote versions" by default and then make it possible to run on a local dxvk repo as a separate option that would not even try to fetch but instead use that path directly.
But not a major issue as long as it is possible to either way I think.
