### ISSUE TITLE
Update to mingw 6.0

### ISSUE THREAD

**Issue by jp7677** [cheald/dxvk-docker#6]
Hi there,

DXVK master requires mingw 6.0 since a few days .https://github.com/doitsujin/dxvk/commit/037f2038f067ed6767ccb350db979824c0604d35
Any chance that you could update your beautiful image?

**Comment by cheald** [comment]
Fixed by https://github.com/cheald/dxvk-docker/pull/7

**Comment by jp7677** [comment]
Works perfectly, thanks a lot!
